# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Edge
        run: |
          wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
          sudo apt-get update
          sudo apt-get install -y microsoft-edge-stable

      - name: Set up Edge WebDriver
        run: |
          wget https://msedgedriver.azureedge.net/115.0.1901.203/edgedriver_linux64.zip
          sudo apt-get install -y unzip
          unzip edgedriver_linux64.zip
          sudo mv msedgedriver /usr/local/bin/

      - name: List files
        run: ls -R src/test/resources/suites/

      - name: Set up environmental variables
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          OAUTH_BASE_URL: ${{ secrets.OAUTH_BASE_URL }}
          ACCESS_TOKEN_URL: ${{ secrets.ACCESS_TOKEN_URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BASE_URL: ${{ secrets.BASE_URL }}
          BROWSER: ${{ secrets.BROWSER }}
          SCOPE: ${{ secrets.SCOPE }}

        # debug environmental variables
        run: |
          # Optional: Output environment variables for debugging
          echo "Environment Variables:"
          echo "CLIENT_ID: $CLIENT_ID"
          echo "CLIENT_SECRET: $CLIENT_SECRET"
          echo "OAUTH_BASE_URL: $OAUTH_BASE_URL"
          echo "ACCESS_TOKEN_URL: $ACCESS_TOKEN_URL"
          echo "USERNAME: $USERNAME"
          echo "PASSWORD: $PASSWORD"
          echo "BASE_URL: $BASE_URL"
          echo "BROWSER: $BROWSER"
          echo "SCOPE: $SCOPE"

      - name: Build and test
        run: mvn clean test

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
